server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA — always serve index.html for unknown routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api/* calls to the backend container on port 5000
    location /api/ {
        proxy_pass         http://localhost:5000;   # use when run in aws
        #proxy_pass         http://capstone-backend:5000; # use when run in local docker container
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
